[package]
name = "wot_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fasthash = "0.4.0"
ibig = "0.3.5"

[dev-dependencies]
proptest = "1.0.0"
